### ISSUE TITLE
[Feature Request] Admin-Only Commands

### ISSUE THREAD

**Issue by phoenixpereira** [compsci-adl/duckbot#23]
### Overview

Create commands that are only accessible to users with admin permissions for commands related to DuckBot setup and configuration, e.g, number of skull react required to post to skullboard.

### Details

Verify user admin status by listing Discord usernames in .env file.

Have admin commands to configure DuckBot including:
`/admin set guild-id`
`/admin set skullboard-channel-id`
`/admin set required reactions`
`/admin reset chat-history`

### Why would this feature be useful?

So that DuckBot's settings can be easily changed without editing code or rerunning deployment actions.

**Comment by CrageJ** [comment]
https://github.com/compsci-adl/duckbot/pull/32 Now includes a database for permanent store of data. Useful for adding/removing admins at runtime.
