### ISSUE TITLE
[Feature Request] Improve help menu

### ISSUE THREAD

**Issue by phoenixpereira** [compsci-adl/duckbot#42]
### Overview

Improve the help menu by having categories for commands and adding buttons.

### Details

See Discord's documentation on [Message Components](https://discord.com/developers/docs/interactions/message-components#message-components) and Discord.py's documentation on [Components](https://discordpy.readthedocs.io/en/stable/interactions/api.html?highlight=button%20component#component).

### Why would this feature be useful?

So that the commands are more organised are listed properly and show subgroups of subgroups (like `/faq fng food`).

### Additional Notes

Can make it similar to Dank Memer's `/help catgeories` command.

<img width="601" alt="image" src="https://github.com/user-attachments/assets/c00fe459-0f71-40e6-964f-e365c4bcb25e">

**Comment by AustinH-adl** [comment]
Hi I have developed a solution for this: 

![image](https://github.com/user-attachments/assets/b40df23d-000f-4030-ba85-fd554790226a)

Just need to iron out a few bugs and improve a bit.

**Comment by AustinH-adl** [comment]
Is this Issue ongoing still? Or should it be closed?

**Comment by phoenixpereira** [comment]
Fixed in #70
